nelmio_api_doc:
    documentation:
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security: 
            - bearerAuth: []  # ✅ This makes JWT global
        info:
            title: Pannasonic feet management API
            description: This is for pannasonic feet management project
            version: 1.0.0
        servers:
            - url: 'http://127.0.0.1:8000'
              description: 'Localhost Server'
    areas: # to filter documented areas
        path_patterns:
            - ^/api